name: midas
description: midas
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       

environment:
  sdk: "3.2.3"



dependencies:
  fl_chart: ^0.36.0
  http: ^1.0.0
  provider: ^6.0.0
  url_launcher: ^6.3.0
  socket_io_client: ^3.0.2



  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

